-- ==========================================
-- DAMENG DM8 INITIALIZATION & TABLES SETUP
-- ==========================================

-- 1. Create Tablespace
CREATE TABLESPACE "FINANCE_DATA" DATAFILE '/home/dmdba/dmdata/DAMENG/FINANCE_01.DBF' SIZE 128 AUTOEXTEND ON NEXT 64;

-- 2. Create User/Schema
CREATE USER "FINANCE_DEMO" IDENTIFIED BY "<DAMENG_PASSWORD>" DEFAULT TABLESPACE "FINANCE_DATA";

-- 3. Grant Permissions
GRANT "PUBLIC", "RESOURCE", "SOI" TO "FINANCE_DEMO";

-- ==========================================
-- BANKING ECOSYSTEM TABLES
-- ==========================================

-- 1. TRANSACTIONS
CREATE TABLE FINANCE_DEMO.TRANSACTIONS (
    TX_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    USER_ID INT,
    MERCHANT_ID INT,
    AMOUNT DECIMAL(10,2),
    TX_TIME TIMESTAMP,
    STATUS VARCHAR(20),
    LOCATION VARCHAR(50)
);

-- 2. CUSTOMERS
CREATE TABLE FINANCE_DEMO.CUSTOMERS (
    CUSTOMER_ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME VARCHAR(100),
    AGE INT,
    CREDIT_LIMIT DECIMAL(10,2),
    RISK_PROFILE VARCHAR(20),
    CREATED_AT TIMESTAMP
);

-- 3. MERCHANTS
CREATE TABLE FINANCE_DEMO.MERCHANTS (
    MERCHANT_ID INT IDENTITY(1,1) PRIMARY KEY,
    MERCHANT_NAME VARCHAR(100),
    CATEGORY VARCHAR(50),
    RISK_LEVEL VARCHAR(20),
    CITY VARCHAR(50),
    CREATED_AT TIMESTAMP
);

-- 4. ACCOUNTS
CREATE TABLE FINANCE_DEMO.ACCOUNTS (
    ACCOUNT_ID VARCHAR(20) PRIMARY KEY,
    CUSTOMER_ID INT,
    ACCOUNT_TYPE VARCHAR(20),
    BALANCE DECIMAL(15,2),
    CURRENCY VARCHAR(10),
    STATUS VARCHAR(20),
    OPENED_AT TIMESTAMP
);

-- ==========================================
-- SAMPLE DATA INSERTION
-- ==========================================

INSERT INTO FINANCE_DEMO.TRANSACTIONS (user_id, amount, status, location) VALUES (1001, 150.50, 'COMPLETED', 'New York');
INSERT INTO FINANCE_DEMO.TRANSACTIONS (user_id, amount, status, location) VALUES (1002, 25000.00, 'FLAGGED', 'London');
INSERT INTO FINANCE_DEMO.TRANSACTIONS (user_id, amount, status, location) VALUES (1003, 75.00, 'PROCESSING', 'Singapore');
COMMIT;
